name: Build and Release Flutter Project

on:
#   push:
#     branches: '**'

  create:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: Get version from tag
      id: version
      run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/v})" >> $GITHUB_ENV


    - name: Build APK
      run: flutter build web

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        RELEASE_VERSION: ${{ env.VERSION }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Automatically built by GitHub Actions
        draft: false
        prerelease: false

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: my-app-release
        path: build/app/outputs/flutter-apk/app-release.apk
