name: Build and deploy flutter app to Oracle VM

on:
  workflow_dispatch:
  create:
  tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - include: build-and-release.yml

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - include: deploy-to-oracle.yml
