name: Build and Release Flutter Project

on:
  workflow_call:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3.3.0

    - name: Setup Flutter
      uses: subosito/flutter-action@v2.8.0
      with:
        channel: 'stable'

    - name: Create Environment File
      run: |
        echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Build for Web
      run: flutter build web
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
        RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ env.RELEASE_VERSION }}
        body: |
          Automatically built by GitHub Actions
        draft: false
        prerelease: false

    - name: Upload web build
      uses: actions/upload-artifact@v3.1.2
      with:
        name: daci
        path: build/web/
        if-no-files-found: error

        
    - name: Print current directory
      run: pwd
    - name: List files in dist folder
      run: ls -la build/web/
