name: Build and deploy flutter app to Oracle VM

on:
  workflow_dispatch:
  create:
    tags:
      - 'v*'

jobs:
  build-and-release:
    uses: ./.github/workflows/build-and-release.yml

  deploy-to-oracle:
    uses: ./.github/workflows/deploy-to-oracle.yml
