name: Copy artifact to Oracle VM

on:
  workflow_dispatch:
#   push:
#     branches:
#       - main

env:
  VM_IP: ${{ secrets.ORACLE_VM_HOST }}
  SSH_KEY: ${{ secrets.ORACLE_VM_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.ORACLE_VM_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install SSH
      run: sudo apt-get update && sudo apt-get install -y openssh-client
      
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H "$VM_IP" >> ~/.ssh/known_hosts
      
#     - name: Copy artifact to Oracle VM
#       run: |
#         scp -r ./dist/* "$SSH_USERNAME@$VM_IP:/var/www/dac"
#         ssh "$SSH_USERNAME@$VM_IP" "sudo systemctl restart apache2"
      
    - name: Test connection
      run: ssh "$SSH_USERNAME@$VM_IP" "echo Connected successfully"
