name: SSH Connection Test
on: [workflow_dispatch]

jobs:
  ssh-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Test SSH Connection
        env:
          HOST: ${{ secrets.VM_HOST }}
          USERNAME: ${{ secrets.ORACLE_VM_USERNAME }}
          PRIVATE_KEY: ${{ secrets.VM_KEY }}
        run: |
          echo "$PRIVATE_KEY" > ssh_key
          chmod 400 ssh_key
          ssh -i ssh_key $USERNAME@$HOST
