name: Deploy to Oracle VM

on:
  workflow_dispatch:
  workflow_call:

env:
  VM_IP: ${{ secrets.ORACLE_VM_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.ORACLE_VM_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.ORACLE_VM_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.3.0
      
      - name: Download artifact
        uses: actions/download-artifact@v3.0.2
        with:
          name: daci
          path: build/web/!
      
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      
      - name: Copy artifact to Oracle VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.VM_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          source: ./build/web/*
          target: /var/www/dac/
      
      - name: Restart Apache server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ env.VM_IP }}
          username: ${{ env.SSH_USERNAME }}
          key: ${{ env.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2
