name: Deploy to Oracle VM

on:
  workflow_dispatch:

env:
  VM_IP: ${{ secrets.ORACLE_VM_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.ORACLE_VM_PRIVATE_KEY }}
  SSH_USERNAME: ${{ secrets.ORACLE_VM_USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install SSH
        run: sudo apt-get update && sudo apt-get install -y openssh-client
      
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
      
#       - name: Copy artifact to Oracle VM
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ env.VM_IP }}
#           username: ${{ env.SSH_USERNAME }}
#           key: ${{ env.SSH_PRIVATE_KEY }}
#           source: ./build/web/
#           target: /var/www/dac
      
      - name: Check dist directory contents
        run: ls -la /build/web/
      
#       - name: Restart Apache server
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ env.VM_IP }}
#           username: ${{ env.SSH_USERNAME }}
#           key: ${{ env.SSH_PRIVATE_KEY }}
#           script: |
#             sudo systemctl restart apache2
