name: Test SSH Connection

on:
  workflow_dispatch:

env:
  SSH_PRIVATE_KEY: ${{ secrets.VM_KEY }}
  KNOWN_HOSTS: ${{ secrets.KNOWN_HOSTS }}
  HOSTNAME: ${{ secrets.HOST }}

jobs:
  test_ssh_connection:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}

    - name: Add host to known hosts
      run: |
        mkdir -p ~/.ssh
        echo "${KNOWN_HOSTS}" > ~/.ssh/known_hosts

    - name: Test SSH connection
      run: |
        ssh -o StrictHostKeyChecking=yes -v user@${HOSTNAME} "echo Connection successful"
